name: architecture_lints
description: A configuration-driven, architecture-agnostic linter for Dart & Flutter.
version: 0.1.4

repository: https://github.com/puntbyte/architecture_workspace/tree/master/packages/architecture_lints
homepage: https://github.com/puntbyte/architecture_workspace/tree/master/packages/architecture_lints
issue_tracker: https://github.com/puntbyte/architecture_workspace/issues

topics:
  - lint
  - architecture
  - code-generation
  - clean-architecture

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0
  code_builder: ^4.10.0
  collection: ^1.19.1
  custom_lint_builder: ^0.8.0
  dart_style: ^3.1.0
  expressions: ^0.2.5+3
  glob: ^2.1.3
  lexicor: ^0.1.4
  meta: ^1.17.0
  mustache_template: ^2.0.1
  path: ^1.9.1
  recase: ^4.1.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  pubspec_parse: ^1.5.0
  test: ^1.26.0
